### ISSUE TITLE
Add 1PLCO2: 1PLANET Carbon Credit

### ISSUE THREAD

**Issue by ClimateFutures01** [maticnetwork/polygon-token-list#109]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: 1PLANET Carbon Credit
Token Symbol: 1PLCO2
Decimals: 18
Polygon Address: 0x14B5eD5dc05e9F7d35104D035719BD65a7EE93E0
Ethereum Address: 0x2E8891AA76743ee96547AcB764a69b87872423f8
Logo URI (svg): https://1planet.app/images/1PL_Token_Logo.svg
Project Name: 1PLANET Marketplace
Project Summary: The www.1PLANET.app enables people and companies to utilize tokenized carbon credits to participate in emissions trading and Carbon Markets 2.0. The 1PLANET token and platform can create EcoNFTs and enable automated carbon offsetting between smart contracts for many use cases.
Project Contact: info@climatefutures.io
Project Website: www.climatefutures.io

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
