### ISSUE TITLE
Add GENESIS: Genesis Worlds

### ISSUE THREAD

**Issue by GAMECreditsChris** [maticnetwork/polygon-token-list#114]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Genesis Worlds
Token Symbol: GENESIS
Decimals: 18
Polygon Address: 0x51869836681BcE74a514625c856aFb697a013797
Ethereum Address:
Logo URI (svg): https://svgshare.com/i/fJk.svg
Project Name: Genesis Worlds
Project Summary: Genesis Worlds is a multi-creator gaming universe, with a diverse community working together to achieve a common goal: A metaverse that will still be growing, evolving, and actively played in 100 years. To achieve this, development and management of Genesis will be decentralized, with governance decisions guided by the Genesis Foundation, and voted on by players using the GENESIS token. Genesis will run as a nonprofit, with all assets owned by and revenue earned by the Genesis Foundation reinvested in the long-term success of the game.
Project Contact: info@gamecredits.org
Project Website: https://genesis.game

Mainnet/Testnet:
Additonal Notes:

**Comment by appumenon** [comment]
@py-zoid Root address is [0x6b6F09997EbFa93F4E111c33825da3b938462FF1](https://etherscan.io/address/0x6b6F09997EbFa93F4E111c33825da3b938462FF1)

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
