### ISSUE TITLE
Update DF: dForce

### ISSUE THREAD

**Issue by Skyge** [maticnetwork/polygon-token-list#116]
**Please only fill in the information you want to update for your token.**

Token Name: dForce (PoS)
Token Symbol: DF
Decimals: 18
Polygon Address: [0x08C15FA26E519A78a666D19CE5C646D55047e0a3](https://polygonscan.com/address/0x08c15fa26e519a78a666d19ce5c646d55047e0a3#code)
Ethereum Address: [0x431ad2ff6a9C365805eBaD47Ee021148d6f7DBe0](https://etherscan.io/address/0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0#code)
Logo URI (svg): https://raw.githubusercontent.com/dforce-network/documents/master/logos/dForce/DF.svg
Project Name: dForce
Project Summary: A complete set of decentralized finance protocols covering assets, lending, and trading, serving as DeFi infrastructure in Web3.
Project Contact: [contact@dforce.network](mailto:contact@dforce.network)
Project Website: https://dforce.network/

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
