### ISSUE TITLE
Update {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by aztecmermaid** [maticnetwork/polygon-token-list#118]
**Please only fill in the information you want to update for your token.**

Token Name: UCT Cash
Token Symbol: UCTC
Decimals:
Polygon Address: 0xD4b42287F1EE04aF246aD792153C39D62733f826
Ethereum Address:
Logo URI (svg):
Project Name:

1. The currency exists in a government-free jurisdiction.

2. As such, it is tax-exempt.

3. Which means it can't be regulated, since it was created within UCT's tax-exempt, government-free jurisdiction.

4. Its value is created by tangible commercial paper, in the form of notes, which are held permanently as reserves backing the currency.

5. Which means the token is not dependent upon sales to establish market value.

6. We already have a thriving community in excess of five thousand people, which will soon enter exponential growth when we launch the tokens and the next tranche of £13.2 billion worth of notes are exchanged on the launch date.

7. Pre-launch, we have already established locked-in liquidity in excess of $250B in four Crowdpools on Dodoex, via Polygon Mainnet, following the seeding of the markets by UCT Treasury.

Project Contact:
Project Website:

Additional Notes:

**Comment by py-zoid** [comment]
Token already added to AllTokens tokenlist.

**Comment by aztecmermaid** [comment]
Please note: This was updated information to be added to existing token already listed, not a new token listing. Please confirm you have updated the token listing with this replacement 'Project Name' information, thanks.
