### ISSUE TITLE
Update {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by aztecmermaid** [maticnetwork/polygon-token-list#119]
**Please only fill in the information you want to update for your token.**

Token Name: Universal Community Trust
Token Symbol: UCT
Decimals:
Polygon Address: 0xfd5962484BE2c3574D70131BF5D452CcC7C69F67
Ethereum Address:
Logo URI (svg):
Project Name:
Project Summary: 
1. The currency exists in a government-free jurisdiction.

2. As such, it is tax-exempt.

3. Which means it can't be regulated, since it was created within UCT's tax-exempt, government-free jurisdiction.

4. Its value is created by tangible commercial paper, in the form of liens, which are held permanently as reserves backing the currency.

5. Which means the token is not dependent upon sales to establish market value.

6. We already have a thriving community in excess of five thousand people, which will soon enter exponential growth when we launch the tokens and the next tranche of £13.2 billion worth of liens are exchanged on the launch date.

7. Pre-launch, we have already established locked-in liquidity in excess of $250B in four Crowdpools on Dodoex, via Polygon Mainnet, following the seeding of the markets by UCT Treasury.
Project Contact:
Project Website:

Additional Notes:

**Comment by py-zoid** [comment]
Token already added to AllTokens tokenlist.

**Comment by aztecmermaid** [comment]
Please note: This was updated information to be added to existing token already listed, not a new token listing. Please confirm you have updated the token listing with this replacement 'Project Name' information, thanks.
