### ISSUE TITLE
Add ICE: Decentral Games ICE

### ISSUE THREAD

**Issue by appumenon** [maticnetwork/polygon-token-list#121]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Decentral Games ICE
Token Symbol: ICE
Decimals: 18
Polygon Address: 0xc6C855AD634dCDAd23e64DA71Ba85b8C51E5aD7c
Ethereum Address: 0x
Logo URI (svg):
Project Name: 
Project Summary:
Project Contact:
Project Website: https://decentral.games/ 

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens TokenList v1.5.1
