### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by appumenon** [maticnetwork/polygon-token-list#123]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: GAME Credits
Token Symbol: GAME
Decimals: 18
Polygon Address: 0x8d1566569d5b695d44a9a234540f68D393cDC40D
Ethereum Address: 0x63f88A2298a5c4AEE3c216Aa6D926B184a4b2437
Logo URI (svg):
Project Name:
Project Summary:
Project Contact:
Project Website: https://gamecredits.org/

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Token already added.
