### ISSUE TITLE
Update MNTO: Minato

### ISSUE THREAD

**Issue by puresims** [maticnetwork/polygon-token-list#131]
**Please only fill in the information you want to update for your token.**

Token Name:
Token Symbol:
Decimals:
Polygon Address:
Ethereum Address:
Logo URI (SVG): https://minatodao.com/wp-content/uploads/2022/03/pcs-96x96.svg
Project Name:
Project Summary:
Project Contact:
Project Website:

Additional Notes:

You can see that this logo is the correct one via CoinGecko, Dextools and our official website. Thank you

**Comment by py-zoid** [comment]
Updated in AllTokens tokenlist v1.8.0.
