### ISSUE TITLE
Add DUST: Distant Universe Stardust Token

### ISSUE THREAD

**Issue by icinsight** [maticnetwork/polygon-token-list#133]
- [ X ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Distant Universe Stardust Token
Token Symbol: DUST
Decimals: 8
Polygon Address: 0x556f501CF8a43216Df5bc9cC57Eb04D4FFAA9e6D
Ethereum Address: 0xbCa3C97837A39099eC3082DF97e28CE91BE14472
Logo URI (svg): https://raw.githubusercontent.com/BlockTimeWorld/crawler/main/icons/dust.svg
Project Name: Dust Token
Project Summary: DUST is a reward token for NFT farming.
Project Contact: contact@dust-token.com
Project Website: https://dust-token.com/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
