### ISSUE TITLE
Add KIWI: KIWI Token

### ISSUE THREAD

**Issue by icinsight** [maticnetwork/polygon-token-list#134]
- [ X ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: KIWI Token
Token Symbol: KIWI
Decimals: 8
Polygon Address: 0x578360AdF0BbB2F10ec9cEC7EF89Ef495511ED5f
Ethereum Address: 0x2BF91c18Cd4AE9C2f2858ef9FE518180F7B5096D
Logo URI (svg): https://raw.githubusercontent.com/BlockTimeWorld/crawler/main/icons/KIWI.svg
Project Name: KIWI Proof-of-Work Token
Project Summary: KIWI is a mineable ERC20/EIP-918 token, and it has no pre-mine. The project was first announced in Bitcointalk in May 6, 2018. Today KIWI is used in payments, NFT trading, engagement, and community development. It can be solo-mined using CPU or GPU.
Project Contact: contact@kiwi-token.com
Project Website: https://kiwi-token.com

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by CrazyCaptian** [comment]
Please update this token, We are utilizing it in our dAPP! Thank you!

**Comment by py-zoid** [comment]
Added to allTokens tokenlist v1.8.0.
