### ISSUE TITLE
Add DATA: Streamr

### ISSUE THREAD

**Issue by fonty1** [maticnetwork/polygon-token-list#135]
- [✅] I understand that token listing is not required to use the Polygon Wallet with a token.

Token Name: Streamr 
Symbol: DATA 
Decimals: 18
 Polygon Address: 0x3a9a81d576d83ff21f26f325066054540720fc34 
Ethereum Address: 0x8f693ca8d21b157107184d29d398a8d082b38b76
Logo URI (svg): https://raw.githubusercontent.com/streamr-dev/design-assets/main/Svg/Marks%20and%20Symbols/Token%20symbols/%24DATA%20new%20token%20symbol.svg
 Project Name: Streamr Network 
Project Summary: Streamr is a decentralized real‑time data network for web3. Create, share and consume data streams on an open, scalable P2P protocol with powerful tools for monetization. As a layer zero protocol, it provides a publish/subscribe messaging framework for decentralized applications built on top.
 Project Contact: contact@streamr.network
 Project Website: https://streamr.network

Mainnet/Testnet: -
 Additonal Notes: -

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
