### ISSUE TITLE
Add LDN: Ludena Protocol

### ISSUE THREAD

**Issue by ludena-protocol** [maticnetwork/polygon-token-list#138]
- [o] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Ludena Protocol
Token Symbol: LDN
Decimals: 18
Polygon Address: 0x7df5638222bbe24cce39f726c3b61cc03610622a
Ethereum Address: 0xb29663aa4e2e81e425294193616c1b102b70a158
Logo URI (svg): https://www.ludenaprotocol.io/data/ludena_protocol_symbol_basic.svg
Project Name: Ludena Protocol
Project Summary: Ludena Protocol is the ultimate blockchain game platform combinding P2E games, NFTs, staking, and guild into one. Users get rewarded for doing simple game related activity such as live streaming, sharing strategies, and even playing mini games in Ludena's guild platform, GameTalkTalk.
Project Contact: official@ludenaprotocol.io
Project Website: https://www.ludenaprotocol.io

Mainnet/Testnet: Mainnet
Additonal Notes: None

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
