### ISSUE TITLE
Update BLOCKS: BLOCKS

### ISSUE THREAD

**Issue by blocks-dao** [maticnetwork/polygon-token-list#143]
- [X ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: BLOCKS
Token Symbol: BLOCKS
Decimals: 18
Polygon Address: 0x983C0083127b9b65000E918b10d65A0F5d7500F5
Ethereum Address: 0x8a6d4c8735371ebaf8874fbd518b56edd66024eb
Logo URI (svg): https://changenow.io/images/sprite/currencies/blocks.svg
Project Name: BLOCKS DAO
Project Summary: BLOCKS is focused on the migration of mainstream commerce into the blockchain space using a standard unit of measure, BLOCKS.
Project Contact: dao@blocks.io
Project Website: https://www.blocks.io/

Mainnet/Testnet: 
Polygon Mainnet Address: 0x983C0083127b9b65000E918b10d65A0F5d7500F5
Mumbai Testnet Address: 0x45719A0919c80ba7af8C4c20b32A9448d022b5FD

Additonal Notes: Social channels available on Etherscan listing: https://etherscan.io/token/0x8a6d4c8735371ebaf8874fbd518b56edd66024eb#tokenInfo

**Comment by py-zoid** [comment]
Updated in allTokens tokenlist v2.3.0
