### ISSUE TITLE
Add GitCoin: GTC

### ISSUE THREAD

**Issue by codenamejason** [maticnetwork/polygon-token-list#146]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: GitCoin
Token Symbol: GTC
Decimals: 18
Polygon Address: 0xdb95f9188479575F3F718a245EcA1B3BF74567EC
Ethereum Address: 0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F
Logo URI (svg): ![Group 51](https://user-images.githubusercontent.com/9419140/164305478-c13be380-142e-4fe8-9adf-ac2c09e8f8d8.svg)
Project Name: Gitcoin DAO
Project Summary: Public Goods Are Good!
Project Contact: Jason Romero
Project Website: https://gitcoin.co

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Updated in AllTokens tokenlist v2.0.2
