### ISSUE TITLE
Add RISE: EverRise

### ISSUE THREAD

**Issue by beneverrise** [maticnetwork/polygon-token-list#15]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: EverRise
Token Symbol: RISE
Decimals: 18
Polygon Address: 0x0cD022ddE27169b20895e0e2B2B8A33B25e63579
Ethereum Address: 0x0cD022ddE27169b20895e0e2B2B8A33B25e63579
Logo URI: https://data.everrise.com/icons/polygon/0x0cd022dde27169b20895e0e2b2b8a33b25e63579.png
Project Name: EverRise
Project Summary: EverRise is a blockchain technology company focused on increasing accessibility to decentralized finance by bringing security and multi-chain solutions to the space through an innovative ecosystem of decentralized applications.

The EverRise Token (RISE), the original buyback token, is a multi-chain collateralized cryptocurrency that serves as a utility token for cross-chain transfers and protects both the ecosystem and investors with its innovative Buyback and Staking protocol.
Project Contact: hello@everrise.com
Project Website: https://www.everrise.com/

Mainnet: https://polygonscan.com/token/0x0cD022ddE27169b20895e0e2B2B8A33B25e63579

**Comment by appumenon** [comment]
This token is not mapped on Polygon Mainnet. Please go through the below docs and raise a mapping request. 
https://docs.polygon.technology/docs/develop/ethereum-polygon/submit-mapping-request/
