### ISSUE TITLE
Add ORC: Orbit Chain

### ISSUE THREAD

**Issue by Jongsic** [maticnetwork/polygon-token-list#154]
- [v] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Orbit Chain
Token Symbol: ORC
Decimals: 18
Polygon Address: 0x1bd5048e0b85c410dd039aa9c05069a9d82488b8
Ethereum Address: 0x662b67d00a13faf93254714dd601f5ed49ef2f51
Logo URI (svg): https://s.ozys.io/icon/orbitchain.svg
Project Name: Orbit Chain
Project Summary: Orbit Chain is a cross-chain project that challenges the limitations of scalability due to the lack of connectivity and limited resources of existing public chains. Orbit Chain has worked to surpass the ever-present scalability and connectivity constraints that have limited traditional public chains. Its improvements and innovations grow user accessibility and convenience so blockchain-based protocols and services can have more real-life integration.
Project Contact: support@orbitchain.io
Project Website: https://orbitchain.io

Mainnet/Testnet: Mainnet
Additonal Notes: Orbit Chain/Orbit Bridge/Orbit Farm

**Comment by py-zoid** [comment]
Added to allTokens v2.2.0
