### ISSUE TITLE
Add {csMATIC}: {ClayStack Staked Matic}

### ISSUE THREAD

**Issue by mohakagr** [maticnetwork/polygon-token-list#159]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: ClayStack Staked MATIC
Token Symbol: csMATIC
Decimals: 18
Polygon Address: 0x7ed6390f38d554B8518eF30B925b46972E768AF8
Ethereum Address: 0x38b7Bf4eeCF3EB530b1529c9401FC37d2a71a912
Logo URI (SVG): https://github.com/ClayStack/media-kit/blob/main/token-images/csMATIC.svg
Project Name: ClayStack
Project Summary: ClayStack is a liquid staking protocol that enables users to earn staking rewards and participate in DeFi simultaneously. Stake your tokens to receive csTokens in return, generating passive rewards without any lockups.
Project Contact: hello@claystack.com
Project Website: https://claystack.com/

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Added to allTokens tokenlist v2.3.0
