### ISSUE TITLE
Add OGUC: Only Graded Coin

### ISSUE THREAD

**Issue by dineshwahmisoft** [maticnetwork/polygon-token-list#161]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Only Graded Coin
Token Symbol: OGUC
Decimals: 18
Polygon Address: 0xB4F74994FCBd60E1bC3603b9a33069eA1b32d4A4
Ethereum Address: 0xB4F74994FCBd60E1bC3603b9a33069eA1b32d4A4
Logo URI (svg): https://onlygradedcoin.com/assets/images/ogc-logo.png
Project Name: Only Graded Coin
Project Summary: A Transparent and decentralized payment solution which projected to be one of the primary payment modes of the Only Graded Ecosystem.
Project Contact: developer@onlygradedcoin.com
Project Website: https://onlygradedcoin.com/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by ThomasDev62** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by appumenon** [comment]
Polygon Address : 0xB4F74994FCBd60E1bC3603b9a33069eA1b32d4A4

**Comment by py-zoid** [comment]
Added token to AllTokens v2.5.0.
