### ISSUE TITLE
Add TCGC: TCGCoin

### ISSUE THREAD

**Issue by CobaltSato** [maticnetwork/polygon-token-list#164]
- [o] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

**Token Name:
Token Name: TCGCoin
Token Symbol: TCGC
Decimals: 18
Polygon Address: 0x44ACD96620B708162af4A90524F29A6839675533
Ethereum Address: 0x2FFdE077455f81E28bAa675a46B9c085740216d4
Logo URI (svg):https://tcgverse-assets.s3.ap-northeast-1.amazonaws.com/tcgcoin_logo.svg
Project Name:TCGCoin
Project Summary:TCGCoin is a token issued by BOBG ltd. A basic token that can be used with services on CryptoSpells and TCGVerse.
Project Contact:[info@cryptogames.co.jp](mailto:info@cryptogames.co.jp)
Project Website:https://tcgverse.gitbook.io/tcgverse/tcgc/tcgcoin

**Comment by py-zoid** [comment]
Added token to AllTokens v2.5.0.
