### ISSUE TITLE
Add UNITY: Cityroots

### ISSUE THREAD

**Issue by joseph-analyticscc** [maticnetwork/polygon-token-list#168]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Cityroots
Token Symbol: UNITY
Decimals: 
Polygon Address: 0x9d7313E23C29e6d314A160A3fF345a2f7Ab0f3f5
Ethereum Address: 0x8fc1A87af3aD30a90cAa197B6c7aDb80d9F2aC44
Logo URI (svg):
Project Name:  Cityroots DAO
Project Summary: With scams, rugpulls, and ever changing market conditions, identifying quality projects is more critical now than ever before. Cityroots DAO aims to be the Amazon of NFT Marketplaces, providing an unprecedented experience on The Vault. All of the revenue goes to the treasury for Cityroots DAO, which is owned by the $UNITY token holders and managed by the City Council (informed by the DAO of 8k Elder Tree Soul NFTs). DAO members can vote to ‘Harvest’ so $UNITY holders can burn their tokens to receive funds from the treasury. 

Project Contact: support@cityroots.io
Project Website: https://cityroots.io/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Added token to AllTokens v2.5.0.
