### ISSUE TITLE
Add FOLO : Alpha Impact

### ISSUE THREAD

**Issue by austin-alphaimpact** [maticnetwork/polygon-token-list#169]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Alpha Impact
Token Symbol: FOLO
Decimals: 18
Polygon Address: 0xeF205F99bD869e74b16050199d54327a0eCd343D
Ethereum Address: 0xb2a63a5dd36c91ec2da59b188ff047f66fac122a
Logo URI (svg): https://alphaimpact.fi/wp-content/uploads/2022/02/logo-horizontal-black.png
Project Name: Alpha Impact
Project Summary: Alpha Impact is a social trading network that allows crypto enthusiasts to view and follow qualified, high performing investors.
Project Contact: austin@alphaimpact.fi
Project Website: https://alphaimpact.fi

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Token was already added to the list. Updated project information in AllTokens v2.5.0.
