### ISSUE TITLE
Update {PLSH}: {Plush}

### ISSUE THREAD

**Issue by dminglv** [maticnetwork/polygon-token-list#172]
Token Name: `Plush`
Token Symbol: `PLSH`
Decimals: `18`
Polygon Address: `0x33044d2c29686795228B89b11D2d34727b8dF9bc `
Ethereum Address: `0x26a22c97Dd308657adA714D9ee0C08233b05fD48 `
Logo URI (svg): `https://raw.githubusercontent.com/PlushFamily/plush-design-assets/main/logos/plush/svg/plush-logo.svg`
Project Name: `Plush Family`
Project Summary: `Intelligent open ecosystem of reliable dapps for families and their members.`
Project Contact: `https://discord.gg/wEguFDBbN6`
Project Website: `https://plush.family`

Additional Notes:

**Comment by py-zoid** [comment]
Updated project information in AllTokens v2.5.0.
