### ISSUE TITLE
Add RFWSTETH: Respawn Finance Wrapped Staked Ethereum

### ISSUE THREAD

**Issue by vloxley** [maticnetwork/polygon-token-list#181]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Respawn Finance Wrapped Staked Ethereum
Token Symbol: RFWSTETH
Decimals: 18
Polygon Address: 0x716ceb4Dc674FB91C4198c50b837F11f6ef75df0
Ethereum Address: 0x07FA101efde726E0956Edd2c4D5C8d3d1A5E9c53
Logo URI (svg): https://assets.respawn.finance/rfwsteth.svg
Project Name: Respawn Finance
Project Summary: Through respawn crypto economics respawn finance provides the base protocol layer between users and (game) content creators.
Project Contact: https://polygonscan.com/address/0xE2D68336944dC53Ac485413518FE9CDa0F197B7b
Project Website: https://respawn.finance/

Mainnet/Testnet: Mainnet
Additonal Notes: /

**Comment by py-zoid** [comment]
Added to AllTokens v2.5.0.
