### ISSUE TITLE
Add {ANX}: {AnimeToken}

### ISSUE THREAD

**Issue by CobaltSato** [maticnetwork/polygon-token-list#186]
- [○] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: AnimeToken
Token Symbol: ANX
Decimals: 18
Polygon Address:  0xe57EAC8b4666032Cfa16b626FfE99403a40b64D3
Ethereum Address: 0x8DaDC5124714bEd53fbc603478De7D4BFEE1fF2a
Logo URI (svg): https://animebank.s3.ap-northeast-1.amazonaws.com/assets/anx.png
Project Name: AnimeBank
Project Summary: Anime Bank is developed based on the system of “Stakes.social (https://stakes.social/ )”, a sponsor platform to support engineers by Dev Protocol that has raised 200M JPY in a year.
We will announce the launch schedule of Anime Bank as soon as we receive an update from the developer.
Project Contact: https://docs.google.com/forms/d/e/1FAIpQLSdoUhSsfRJO2cB4ifoZaZfg6mUaKm2Oo6cXCYo4QF2UFsVk1w/viewform
Project Website: https://anime-bank.com/ (coming soon)

**Comment by py-zoid** [comment]
Added to AllTokens v2.8.0.
