### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by Akansh-Stader** [maticnetwork/polygon-token-list#196]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Stader MaticX
Token Symbol: MaticX

Polygon Address: 0xfa68fb4628dff1028cfec22b4162fccd0d45efb6
Ethereum Address: 0xf03a7eb46d01d9ecaa104558c732cf82f6b6b645

Project Name: Stader
Project Contact: Akansh Mathur (akansh.mathur@staderlabs.com)
Project Website: https://staderlabs.com/

Mainnet: https://polygon.staderlabs.com/

**Comment by py-zoid** [comment]
Added to AllTokens v2.8.0.
