### ISSUE TITLE
Add {SHIBX}: {Shibex}

### ISSUE THREAD

**Issue by yosefede06** [maticnetwork/polygon-token-list#20]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Shibex
Token Symbol: SHIBX
Decimals: 18
Polygon Address: 0xe04e81331bdcbfbf2d1342714812d546a55cb6dc
Ethereum Address: 
Logo URI: https://ipfs.io/ipfs/QmVrp6adhptZfNhkLazfkyPLwMnL8EVULHPsfhGXcnPEJC
Project Name: Shibex
Project Summary: Shibex is a Gamefi platform of arcade games where SHIBX is the token that allow players to play and bet with a new mechanism called play2burn
Project Contact: yosefede06@gmail.com
Project Website: www.shibex.game

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by appumenon** [comment]
Currently we are adding only adding mapped tokens. We will consider this this in the next iteration.
