### ISSUE TITLE
Add CBK: Cobak Token

### ISSUE THREAD

**Issue by jokimkhj** [maticnetwork/polygon-token-list#200]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Cobak Token
Token Symbol: CBK
Decimals: 18
Polygon Address: 0x4EC203dD0699Fac6adAF483CDd2519BC05D2c573
Ethereum Address: 0xD85a6Ae55a7f33B0ee113C234d2EE308EdeAF7fD
Logo URI (svg): https://storage.cobak.co/logo/cbk_symbol.svg
Project Name: Cobak
Project Summary:
Project Contact: partner@cobak.co
Project Website: https://cobak.co.kr/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens v3.0.0.
