### ISSUE TITLE
Update (REMOVE) CGT : CACHE Gold

### ISSUE THREAD

**Issue by cache-gold** [maticnetwork/polygon-token-list#204]
**Please only fill in the information you want to update for your token.**

Token Name: CACHE Gold
Token Symbol: CGT
Decimals: 8
https://polygonscan.com/token/0xc17d249c8a675c2e67a5b305a3e6b23cc45d81aa

Additional Notes: Please remove this token from the Polygon Bridge UI, we have our own bridge at: https://bridge.cache.gold. The Polygon Bridge will not work and will result in a loss of user funds.

**Comment by py-zoid** [comment]
Removed in tokenlist v3.0.0.
