### ISSUE TITLE
Add APE: Apecoin

### ISSUE THREAD

**Issue by jtchoi89** [maticnetwork/polygon-token-list#207]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Apecoin
Token Symbol: APE
Decimals: 18 
Polygon Address: 0xb7b31a6bc18e48888545ce79e83e06003be70930
Ethereum Address: 0x4d224452801aced8b2f0aebe155379bb5d594381
Logo URI (svg): https://wallet-asset.matic.network/img/tokens/ape.svg
Project Name: Project WL
Project Summary: Bored Ape Game
Project Contact: jongtae.choi@nway.com
Project Website: 

Mainnet/Testnet:
Additonal Notes: We want to add Apecoin to the Default Token List to facilitate users to bridge/swap ETH Apecoin to Polygon Apecoin more easily.

**Comment by py-zoid** [comment]
Added to AllTokens v3.0.0.

**Comment by alswrmani** [comment]
> * [ ] أدرك أن قائمة الرموز المميزة ليست مطلوبة لاستخدام محفظة Polygon مع رمز مميز.
> 
> **يرجى تقديم المعلومات التالية للرمز المميز الخاص بك.**
> 
> اسم الرمز المميز: رمز رمز Apecoin: الكسور العشرية لـ APE: 18 عنوان المضلع: 0xb7b31a6bc18e48888545ce79e83e06003be70930 عنوان Ethereum: 0x4d224452801aced8b2f0aebe155379bb5d594381 Logo URI (svg): https://wallet-asse t.matic.network/img/tokens/ape.svg [اسم](https://wallet-asset.matic.network/img/tokens/ape.svg) المشروع: مشروع WL المشروع ملخص: مشروع لعبة Bored Ape، جهة الاتصال: [jongtae.choi@nway.com](mailto:jongtae.choi@nway.com) ، موقع المشروع:
> 
> الشبكة الرئيسية/Testnet: ملاحظات إضافية: نريد إضافة Apecoin إلى قائمة الرموز الافتراضية لتسهيل على المستخدمين ربط/تبديل ETH Apecoin إلى Polygon Apecoin بسهولة أكبر.
address wallet my
0x828342054a25727406E24432F0314B76Fbfa3ED1
