### ISSUE TITLE
Add TRIPS: TRIPS

### ISSUE THREAD

**Issue by lucadgtrip** [maticnetwork/polygon-token-list#25]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: TRIPS
Token Symbol: TRIPS
Decimals: 18
Polygon Address: 0x77F0F7d657f362C4b703417B800B83B989a288a2
Ethereum Address:  0x1350fbe8ce27762ec19134bf8fc405a427fe9bf1
Logo URI: https://gateway.pinata.cloud/ipfs/QmVxZCAvxab8bUhaScwqw6NWABmqz4jmjJ3qnYUbdKweEf
Project Name: Trips Community
Project Summary: Open Protocol for Web3 in Travel
Project Contact: info@tripscommunity.com
Project Website: https://www.tripscommunity.com/

Mainnet/Testnet: Mainnet
Additonal Notes: mapped via https://mapper.polygon.technology

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
