### ISSUE TITLE
Add PIN: Pinjour

### ISSUE THREAD

**Issue by jfornear** [maticnetwork/polygon-token-list#27]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Pinjour
Token Symbol: PIN
Decimals: 18
Polygon Address: 0x1d5278cbd93ff50260fddc93282e2e67ca3317c9
Ethereum Address: 0x76c9a9583bda3ac6440fc153c7ffd89f99823a2c
Logo URI: https://d26jz7p3kula4l.cloudfront.net/static/img/pinjour-192x192.png
Project Name: Pinjour
Project Summary: Photo maps for explorers
Project Contact: jesse@pinjour.com
Project Website: https://pinjour.com

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
