### ISSUE TITLE
Add CNDL: Candle

### ISSUE THREAD

**Issue by samisbakedham** [maticnetwork/polygon-token-list#28]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Candle
Token Symbol: CNDL
Decimals: 18
Polygon Address: 0x5423063af146F5abF88Eb490486E6B53FA135eC9
Ethereum Address: 0xbc138bD20C98186CC0342C8e380953aF0cb48BA8
Logo URI: https://i.ibb.co/86yLQRZ/candlelogo.png
Project Name: Candle
Project Summary: Decentralizing Religion
Project Contact: contact@candlelabs.org
Project Website: https://candlelabs.org

Mainnet/Testnet: Mainnet 
Additonal Notes: Featured Project

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
