### ISSUE TITLE
Add TOWER: TowerToken

### ISSUE THREAD

**Issue by sagarduwal** [maticnetwork/polygon-token-list#29]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

Token Name: Tower Token
Token Symbol: TOWER
Decimals: 18
Polygon Address: 0x2bC07124D8dAc638E290f401046Ad584546BC47b
Ethereum Address: 0x1C9922314ED1415c95b9FD453c3818fd41867d0B
Logo URI: https://crazydefenseheroes.com/static/media/logo-tower.2bca4bdd.svg
Project Name: Tower Token
Project Summary: The TOWER Token is a utility token for the TOWER Platform that comprises the token, the Free-to-Play games in the Crazy Kings franchise and the blockchain game.
Project Contact: towertoken@crazydefenseheroes.com
Project Website: https://crazydefenseheroes.com/

Mainnet/Testnet:
Additonal Notes: Mapped with https://mapper.polygon.technology/ in mainnet and testnet
For testnet latest tower address: 0xbb2c9203c8d0c169638c6391da2828f0278231af

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
