### ISSUE TITLE
Add MEED: Meeds

### ISSUE THREAD

**Issue by plamarque** [maticnetwork/polygon-token-list#30]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name:Meeds
Token Symbol:MEED
Decimals:18
Polygon Address:0x6aca77cf3bab0c4e8210a09b57b07854a995289a
Ethereum Address:0x8503a7b00b4b52692cc6c14e5b96f142e30547b7
Logo URI:https://github.com/Meeds-io/.github/raw/main/profile/meeds-256x256.png
Project Name:Meeds
Project Summary:Meeds DAO aims at reinventing the employment relationship, bridging the gap between traditional corporations and DAOs through a new decentralized work paradigm. The Meed is the currency that is earned by workers by proof of engagement.

Project Contact:info@meeds.io
Project Website:https://meeds.io

Mainnet/Testnet:Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
