### ISSUE TITLE
Add SURE: inSure DeFi

### ISSUE THREAD

**Issue by inSureToken** [maticnetwork/polygon-token-list#31]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: inSure DeFi
Token Symbol: SURE
Decimals: 18
Polygon Address: 0xF88332547c680F755481Bf489D890426248BB275
Ethereum Address: 0xcb86c6a22cb56b6cf40cafedb06ba0df188a416e
Logo URI: https://insuretoken.net/images/logo-grey-circle.png
Project Name: inSure DeFi
Project Summary: inSure DeFi is a Decentralized Insurance Ecosystem, trusted by thousands of community members to protect their crypto portfolios from scams, exchange closures, and drastic devaluations. inSure DeFi provides insurance solutions for the crypto space to stabilize and secure Crypto & DeFi portfolios.

Project Contact: https://github.com/inSureToken/SmartContract/blob/master/inSure.sol
Project Website: https://insuretoken.net/

Mainnet/Testnet: Mainnet
Additional Notes: https://fairyproof.com/doc/iSureDeFi-Audit-Report-102121.pdf

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
