### ISSUE TITLE
Add DRINK: Beverage Token

### ISSUE THREAD

**Issue by CaptainMorgan8** [maticnetwork/polygon-token-list#33]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Beverage Token
Token Symbol: DRINK
Decimals: 18
Polygon Address: 0x366a39a2f73de32df17cc9bdd027aa054f6ba9cb
Ethereum Address: 0x9257fb8fab616867cEe67C3289547403617B1938
Logo URI: https://github.com/Beverage-Finance/beverage-docs/blob/main/assets/beverage-token-logos/beverage-200X200.png
Project Name: Beverage Finance
Project Summary: Beverage Finance is a decentralized asset manager for structured products. Similar to Sushi and Yearn, Beverage is a fair launch, no premine project that is governed by the vote of the community. 80% of fees are sold to $DRINK and distributed to $xDRINK stakers. Beverage is developer first, anyone can create a strategy and launch it on Beverage with minimal governance and receive 20% of fees.
Project Contact: support@beverage.finance
Project Website: matic.beverage.finance

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
logoURI: https://raw.githubusercontent.com/Beverage-Finance/beverage-docs/main/assets/beverage-token-logos/beverage-200X200.png

**Comment by py-zoid** [comment]
Included in ALlTokens v1.2.0.
