### ISSUE TITLE
Add WCHI: Wrapped CHI

### ISSUE THREAD

**Issue by domob1812** [maticnetwork/polygon-token-list#34]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Wrapped CHI
Token Symbol: WCHI
Decimals: 8
Polygon Address: 0xE79feAAA457ad7899357E8E2065a3267aC9eE601
Ethereum Address: 0x6DC02164d75651758aC74435806093E421b64605
Logo URI: https://arweave.net/cLtOpcOcgshTnA3aWe8a1lKRG0baZHfWGsi1mq5Cgt4
Project Name: Xaya
Project Summary: A platform for scalable and fully decentralised games and applications.
Project Contact: andy@xaya.io, daniel@xaya.io
Project Website: https://xaya.io/

Mainnet/Testnet: This request is for our token on mainnets.
Additonal Notes: The contract of our token, all addresses and other information can be found here: https://github.com/xaya/wchi

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
