### ISSUE TITLE
Add IND: Indorse 

### ISSUE THREAD

**Issue by gaurangtorvekar** [maticnetwork/polygon-token-list#35]
- I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Indorse
Token Symbol: IND
Decimals: 18
Polygon Address: 0x9611452965b63cFeA2C9774e5386AB6D4F0abf16
Ethereum Address: 0xf8e386EDa857484f5a12e4B5DAa9984E06E73705
Logo URI: https://drive.google.com/file/d/1Wbw4t_hibR5zMBdrLysvhfJvSIe34q9N/view?usp=sharing
Project Name: Indorse
Project Summary: Indorse is a Blockchain-based coding assessment solution being used by Enterprise companies, banks and universities in Singapore and South East Asia.
Project Contact: info@indorse.io
Project Website: https://ecosystem.indorse.io/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
