### ISSUE TITLE
Add GER: Germoney

### ISSUE THREAD

**Issue by friedhelmensch** [maticnetwork/polygon-token-list#39]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Germoney
Token Symbol: GER
Decimals: 2
Polygon Address: 0x03a68f78107d102d26353e5476733b067950bab6
Ethereum Address: 0x844Af22fBEC4D1bb9C062F33D29e4Ad8d0EFc01D
Logo URI: https://www.germoney.cash/static/media/logo.7c3abfc4.png
Project Name: Germoney
Project Summary: Germoney represents the old currency of Germany. The D-Mark. Therefore the total supply equals the remaining D-Mark existing in circulation.
Project Contact: therealgermoney@protonmail.com
Project Website: https://germoney.cash

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
