### ISSUE TITLE
Add MEGA: Megaverse

### ISSUE THREAD

**Issue by ernefinance** [maticnetwork/polygon-token-list#40]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Megaverse
Token Symbol: MEGA
Decimals: 18
Polygon Address: 0xD87958D9Cc146aBe382Ee20D1EF278321E61ADe9
Ethereum Address: 0xCF9b27399447f92462Dad69491edbA304a063591
Logo URI: https://imgur.com/1pDWnjT
Project Name: Megaverse
Project Summary: Where social media users and the world’s most vibrant global communities enter the metaverse
Project Contact: mo@megaverse.game
Project Website: https://megaverse.game/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
logoURI: https://i.imgur.com/1pDWnjT.jpeg

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
