### ISSUE TITLE
Add {RVF}: {RocketX}

### ISSUE THREAD

**Issue by KiranMannam** [maticnetwork/polygon-token-list#41]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: RocketX
Token Symbol: RVF
Decimals: 18
Polygon Address: 0x2ce13e4199443fdfff531abb30c9b6594446bbc7
Ethereum Address: 0xdc8af07a7861bedd104b8093ae3e9376fc8596d2
Logo URI: https://drive.google.com/file/d/106QzWJ-42p2FVsgZQ4pVCw_cTTAudU39/view?usp=sharing
Project Name: RocketX exchange
Project Summary: We are building "The Skyscanner for Crypto". RocketX exchange aggregates both the Centralised and Decentralised Crypto Exchanges and makes it easy for the user to find the best rates to swap tokens across different exchanges with lowest gas fee (Save up to 80%).

Project Contact: contact@rocketvaults.io
Project Website: https://rocketx.exchange/

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
