### ISSUE TITLE
Add KNIGHT : Forest Knight

### ISSUE THREAD

**Issue by Chrono-Games** [maticnetwork/polygon-token-list#43]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Forest Knight
Token Symbol: KNIGHT
Decimals: 18
Polygon Address: 0x4455eF8B4B4A007a93DaA12DE63a47EEAC700D9D
Ethereum Address: 0x4455eF8B4B4A007a93DaA12DE63a47EEAC700D9D
Logo URI: https://s2.coinmarketcap.com/static/img/coins/64x64/11324.png
Project Name: Forest Knight
Project Summary: Forest Knight is a Free2Play Turn-Based Strategy for mobile powered by NFTs and the utility token $KNIGHT
Project Contact: support@chronogames.net
Project Website: www.forestknight.io

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
