### ISSUE TITLE
Add {LEPA}: {LEPASA}

### ISSUE THREAD

**Issue by Lepasa** [maticnetwork/polygon-token-list#44]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: LEPASA
Token Symbol: LEPA
Decimals: 18 
Polygon Address: 0xF9a4BBAa7fA1DD2352F1A47d6d3fcfF259A6D05F
Ethereum Address: 0xbBa6C7c7d673c48d90069ad2e9d2fE587fcB6bc3
Logo URI: https://www.lepasa.com/assets/img/logo_256.png
Project Name: LEPASA
Project Summary: Lepasa project offers finest ever mythological characters in the form of 3D game ready NFTs. Lepasa NTFs can be purchased from LEPA token which is an ERC20 token on Ethereum chain and bridged to Polygon and BSC.
Project Contact: info@lepasa.com
Project Website: https://www.lepasa.com/

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
