### ISSUE TITLE
Add CIV: Civilization

### ISSUE THREAD

**Issue by DexMan100** [maticnetwork/polygon-token-list#45]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Civilization
Token Symbol: CIV
Decimals: 18
Polygon Address: 0x42F6bdCfd82547e89F1069Bf375aa60e6c6c063d
Ethereum Address: 0x37fE0f067FA808fFBDd12891C0858532CFE7361d
Logo URI: https://app.civfund.org/CIV_logo_txt_192x192.png
Project Name: Civilization
Project Summary: The first DeFi trading system achieving functional parity with Centralized Exchanges, at lower gas costs than any other platform
Project Contact: civ@civfund.org
Project Website: https://civfund.org

Mainnet/Testnet: Ethereum, Polygon, Kovan, Rinkeby, Mumbai
Additonal Notes: (<-- there is a typo here, missing an "i")

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
