### ISSUE TITLE
Add MOVE: Move

### ISSUE THREAD

**Issue by amozgov** [maticnetwork/polygon-token-list#48]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Move
Token Symbol: MOVE
Decimals: 18
Polygon Address: 0x521CddC0CBa84F14c69C1E99249F781AA73Ee0BC
Ethereum Address: 0x3fa729b4548becbad4eab6ef18413470e6d5324c
Logo URI: https://assets.coingecko.com/coins/images/13719/small/o0KIvs7T_400x400.jpg?1617672818
Project Name: MoverDAO
Project Summary: Mover is building the first metaverse savings card. It is an NFT card that is metaverse-ready, comes with automated DeFi Savings, and a crypto debit card. All in one place.

Mover offers multiple products: Savings allow for the easiest non-custodial and permissionless savings on USDC. Crypto debit card - is a crypto debit card. Spend your crypto anywhere with a Visa card. Multichain savings allow users to deposit into the easiest non-custodial and permissionless savings from any and to any supported chain. 

Mover is a community-first and community-led project. There are no investors or insiders. We are open and friendly. So come and join us on our journey in a metaverse.
Project Contact: hello@viamover.com
Project Website: https://viamover.com

Mainnet/Testnet: Mainnet
Additonal Notes: We are already bridged. However, we would want to be on the whitelist, as well as the token symbol and name to be updated accordingly with the rebranded that happened on March 31st, 2021 https://viamover.com/news_and_promos/holyheld_is_moving

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
