### ISSUE TITLE
Add STACK: Stacker Ventures Token

### ISSUE THREAD

**Issue by JonasBayes** [maticnetwork/polygon-token-list#49]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Stacker Ventures Token
Token Symbol: STACK
Decimals: 18
Polygon Address: 0xccBe9B810d6574701d324fD6DbE0A1b68f9d5bf7
Ethereum Address: 0xe0955f26515d22e347b17669993fcefcc73c3a0a
Logo URI: https://assets.coingecko.com/coins/images/14218/small/stack.jpg?1615000614
Project Name: Stacker Ventures
Project Summary: Stacker Ventures is a community-run protocol for initiating and managing pooled capital on the blockchain.
Project Contact: communications@stacker.vc
Project Website: https://stacker.vc

Mainnet/Testnet: Mainnet
Additonal Notes: Thanks guys!

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
