### ISSUE TITLE
Add VOLT: Voltage

### ISSUE THREAD

**Issue by billyshipp** [maticnetwork/polygon-token-list#53]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Voltage
Token Symbol: VOLT
Decimals: 18
Polygon Address: Oxe8a05e85883f9663b18a38d7aa89853deaba56e3
Ethereum Address: 0xffbf315f70e458e49229654dea4ce192d26f9b25
Logo URI: https://assets.coingecko.com/coins/images/18515/small/volt.png?1632219924
Project Name: SupDucks
Project Summary: VOLT is a utility token that is used to fuel mechanics in the SupDucks universe. The mechanics include things like breeding, forging, metadata upgrades, gaming, content unlocks and future drops. Additionally, it serves as community rewards for participating in and contributing to the SupDucks community. Volt is also used to redeem SupDucks branded merch and will be integral in the forthcoming SupDucks metaverse.
Project Contact: sup@megavoltcorp.com
Project Website: supducks.com

Mainnet/Testnet: Mainnet
Additonal Notes: Sup

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
