### ISSUE TITLE
Add {XLVI}: {PRESIDENT BRANDON TOKEN}

### ISSUE THREAD

**Issue by noonercoin** [maticnetwork/polygon-token-list#54]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: President Brandon Token
Token Symbol: XLVI
Decimals: 2
Polygon Address: 0x40Dc7491CB56FF50a9913f7228feAe802dB99920
Ethereum Address: 0x9b3007568341382b2De292d056fF7E41870d0a0e
Logo URI: https://twitter.com/XLVIcrypto/photo
Project Name: President Brandon Token
Project Summary: An ERC20 token tailored with a utility for conservative crypto traders and consumers 
Project Contact: JP
Project Website: https://www.presidentbrandontoken.com/

Mainnet/Testnet: Project currently on Polygon Mainnet via liquidity pool (MATIC: XLVI)
Additonal Notes:

**Comment by appumenon** [comment]
Please provide an email address or social handle as the project contact

**Comment by noonercoin** [comment]
Please use: ***@***.***


Thank you,
Jay

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
