### ISSUE TITLE
Add MASQ: MASQ

### ISSUE THREAD

**Issue by kauri-hero** [maticnetwork/polygon-token-list#55]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: MASQ
Token Symbol: MASQ
Decimals: 18
Polygon Address: 0xee9a352f6aac4af1a5b9f467f6a93e0ffbe9dd35
Ethereum Address: 0x06F3C323f0238c72BF35011071f2b5B7F43A054c
Logo URI: https://github.com/MASQ-Project/MASQ-contract/raw/master/MASQ%20Logo%20Blue%20Solo%20Transparent.png
Project Name: MASQ Network
Project Summary: The MASQ software offers users a true privacy web3.0 browsing experience, based on a peer to peer mesh network. Users can earn cryptocurrency by supporting the network, and provides Internet freedom for users worldwide.
Project Contact: KauriHero Project Manager, kaurihero@masq.ai
Project Website: https://masq.ai

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in All Tokens v1.2.0.
