### ISSUE TITLE
Add INSUR: InsurAce

### ISSUE THREAD

**Issue by zy-insurace** [maticnetwork/polygon-token-list#56]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: InsurAce
Token Symbol: INSUR
Decimals: 18
Polygon Address: 0x8a0e8b4b0903929f47C3ea30973940D4a9702067
Ethereum Address: 0x544c42fBB96B39B21DF61cf322b5EDC285EE7429
Logo URI: https://app.insurace.io/asset/token/insur.png
Project Name: InsurAce
Project Summary: InsurAce is a decentralized insurance protocol, aiming to provide reliable, robust, and carefree DeFi insurance services to DeFi users, with a low premium and sustainable investment returns.
Project Contact: contact@insurace.io
Project Website: https://www.insurace.io/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in All Tokens v1.2.0.
