### ISSUE TITLE
Add ORBS: Orbs Token

### ISSUE THREAD

**Issue by mattanerder** [maticnetwork/polygon-token-list#57]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Orbs Token
Token Symbol: ORBS
Decimals: 18
Polygon Address: 0x614389EaAE0A6821DC49062D56BDA3d9d45Fa2ff
Ethereum Address: 0xff56Cc6b1E6dEd347aA0B7676C85AB0B3D08B0FA
Logo URI: https://raw.githubusercontent.com/orbs-network/graphical-assets/main/orbs/ethereum/token/logo256.png 
Project Name: Orbs Network
Project Summary: Orbs is a public blockchain infrastructure designed for mass usage applications and close integration with EVM-based L1’s and L2’s such as Ethereum and Binance SmartChain. Orbs offers the winning blockchain stack, providing the  perfect mix of performance, cost, security and ease of  use, while harnessing the power of community,  decentralization and distribution. Combining scalability, low fees and isolation between virtual chains with a top-grade developer experience, online IDE and smart contracts in familiar languages, Orbs provides developers the perfect mix of performance, cost, security and ease of use. 
Orbs’ advanced architecture puts it in a unique position to work in conjunction with  EVM-based L1s and L2s by serving as a separate execution layer that runs decentralized applications that enrich the capabilities of EVM-based smart contracts. These L3 applications can be executed by a public network of permissionless validators using POS powered by the ORBS token. The new layer provided by the Orbs blockchain opens the door for many exciting and innovative applications in the DeFi space which are currently not available.
Founded in 2017, Orbs is being developed by a dedicated team of more than 30 people out of its offices in Tel Aviv, Israel, London, UK, Singapore, Japan, and South Korea.
Project Contact: Ran Hammer, VP BizDev - ranh@orbs.com
Project Website: https://www.orbs.com/ 

Mainnet/Testnet: https://prism.orbs.network/ 
Additonal Notes:

**Comment by py-zoid** [comment]
Included in All Tokens v1.2.0.
