### ISSUE TITLE
Add GIST:GISTCOIN

### ISSUE THREAD

**Issue by nollytainment** [maticnetwork/polygon-token-list#58]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: GISTCOIN
Token Symbol: GIST
Decimals: 18
Polygon Address: 0xF6db73D0495Fe4648d494046cCbdc5625F2740F0
Ethereum Address: 0x6cd775540cce9adb01872db9f794142f53595c71
Logo URI: https://etherscan.io/token/images/gistcoin_32.png
Project Name: Gistcoin Payment
Project Summary: Gistcoin is a utility token for all influencers, streamers, musicians, artists, brands, and content creators from all backgrounds who create content across social media communities. We believe that a decentralized token system allows for all creators – including creators from underrepresented groups – to have direct access to their fans and monetization methods.

Project Contact: hello@gistcoin.com
Project Website: gistcoin.io
Mainnet/Testnet: main net
Additonal Notes:

**Comment by py-zoid** [comment]
Included in All Tokens v1.2.0.
