### ISSUE TITLE
Add {0xMR}: {0xMonero}

### ISSUE THREAD

**Issue by JThompson123** [maticnetwork/polygon-token-list#60]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: 0xMonero
Token Symbol: 0xMR
Decimals: 18
Polygon Address: 0x52ede6bba83b7b4ba1d738df0df713d6a2036b71
Ethereum Address: 0x035df12e0f3ac6671126525f1015e47d79dfeddf
Logo URI: https://avatars.githubusercontent.com/u/65775032?v=4
Project Name: 0xMonero
Project Summary: 0xMonero is a minable privacy focused project on Ethereum, Polygon, Fantom, BNB and other popular chains. $0xMR can be used in a variety of privacy DApps and in our partner casinos: LNOcasino & Betcrypt365. The project is managed by MotherbrainDAO and development is by SemillaLabs.
Project Contact: 0xMonero@gmail.com
Project Website: https://0xMonero.com

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
