### ISSUE TITLE
Add {BTU}: {BTU Protocol}

### ISSUE THREAD

**Issue by appyhour770** [maticnetwork/polygon-token-list#61]
- [Y] I understand that token listing is not required to use the Polygon Wallet with a token.

Token Name: BTU Protocol
Token Symbol: BTU
Decimals: 18
Polygon Address: 0xfdc26cda2d2440d0e83cd1dee8e8be48405806dc
Ethereum Address: 0xb683D83a532e2Cb7DFa5275eED3698436371cc9f
Logo URI: https://btu-protocol.com/images/log-BTU-256w.png
Project Name: BTU Protocol
Project Summary: BTU Protocol provides asset, software & APIs to create frictionless bankless incentives, send rewards and manage redemptions.
Project Contact: support@btu-protocol.com
Project Website: https://btu-protocol.com

Mainnet/Testnet: 
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
