### ISSUE TITLE
Add {CRT}: {Cryptopia Token}

### ISSUE THREAD

**Issue by jonbeau** [maticnetwork/polygon-token-list#62]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Cryptopia Token
Token Symbol: CRT
Decimals: 18
Polygon Address: 0x7348565F0A5077252D310392C3CeCD8dB87a7704
Ethereum Address: 0xABdD22dFE5Db2be20262050523470B650E91F246
Logo URI: https://cryptopia.com/images/icons/icon_CRT.png
Project Name: Cryptopia
Project Summary: Cryptopia is a ground-breaking blockchain-driven metaverse. Join a rising nation-state where you can build either a business empire or a successful profession. Stake and collect NFTs. Buy, sell, and earn using an integrated wallet. P2E is as easy as browsing the web!
Project Contact: info@cryptopia.com
Project Website: https://www.cryptopia.com

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
