### ISSUE TITLE
Add BLANK: BlockWallet

### ISSUE THREAD

**Issue by ImanH** [maticnetwork/polygon-token-list#64]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: GoBlank Token
Token Symbol: BLANK
Decimals: 18
Polygon Address: 0xf4C83080E80AE530d6f8180572cBbf1Ac9D5d435
Ethereum Address: 0x41A3Dba3D677E573636BA691a70ff2D606c29666
Logo URI: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x41A3Dba3D677E573636BA691a70ff2D606c29666/logo.png
Project Name: BlockWallet
Project Summary: BlockWallet is a privacy-focused non-custodial crypto wallet. Besides full privacy functionality, BlockWallet comes packed with an array of features that go beyond privacy for a seamless user experience. Reclaim your financial privacy. Get BlockWallet.
Project Contact: https://twitter.com/GetBlockWallet
Project Website: BlockWallet.io

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
