### ISSUE TITLE
Add EQZ:Equalizer

### ISSUE THREAD

**Issue by abancu** [maticnetwork/polygon-token-list#65]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Equalizer
Token Symbol: EQZ
Decimals: 18
Polygon Address: 0xEAf631ac57F3CDDDd261770dD47F85066131a156
Ethereum Address: 0x1Da87b114f35E1DC91F72bF57fc07A768Ad40Bb0
Logo URI: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x1Da87b114f35E1DC91F72bF57fc07A768Ad40Bb0/logo.png
Project Name: Equalizer
Project Summary: Equalizer represents the next generation marketplace for flash loans, a dedicated platform that brings together liquidity providers and borrowers. On one side we incentivize LPs for staking their funds in secure vaults, by receiving more tokens coming from the fees of the flash loans provided. Additionally, the LPs are automatically part of our yield farming program, designed to stimulate long-term liquidity providers. On the other side, borrowers are provided with a plethora of liquid pools (vaults) that bring more advantages than any other competitor in the market: lower fees, a wider range of tokens, a minimum level of available liquidity, reliability in all market conditions, available on multiple chains.
Project Contact: info@equalizer.finance
Project Website: https://equalizer.finance/

Mainnet/Testnet: mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
