### ISSUE TITLE
Add PLR: Pillar

### ISSUE THREAD

**Issue by SaltyCucumber** [maticnetwork/polygon-token-list#66]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

Token Name: Pillar
Token Symbol: PLR
Decimals: 18
Polygon Address: 0xa6b37fC85d870711C56FbcB8afe2f8dB049AE774
Ethereum Address: 0xe3818504c1B32bF1557b16C238B2E01Fd3149C17
Logo URI: https://etherscan.io/token/images/pillar_32.png
Project Name: Pillar
Project Summary: Pillar is a community-run smart wallet supporting Ethereum and EVM-compatible chains - Polygon, xDai & Binance Smart Chain and Avalanche - in a unified multichain experience. Powered by Etherspot and governed by the DAO through its own native token - PLR. Pillar aims to become a one stop DeFi experience.
Project Contact: https://twitter.com/pillarwallet
Project Website: https://www.pillar.fi/

Mainnet/Testnet: Mainnet

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
