### ISSUE TITLE
Add EFI: Efinity Token

### ISSUE THREAD

**Issue by blockchainguyy** [maticnetwork/polygon-token-list#67]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Efinity Token
Token Symbol: EFI
Decimals: 18
Polygon Address: 0x891254dbb6112cf938d16c1880540b8469df6c0e
Ethereum Address: 0x656c00e1bcd96f256f224ad9112ff426ef053733
Logo URI: https://cdn.efinity.io/static/logo.svg
Project Name: Efinity
Project Summary: Efinity is a cross-chain superhighway bringing NFTs to Polkadot. (Learn More: https://efinity.io/whitepaper/company)
Project Contact: [support@efinity.io](mailto:support@efinity.io)
Project Website: https://efinity.io/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
