### ISSUE TITLE
Add FLEATO: Fleato coin

### ISSUE THREAD

**Issue by manosamy** [maticnetwork/polygon-token-list#68]
- [x ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Fleato coin
Token Symbol: FLEATO
Decimals: 18
Polygon Address: 0x6804b07d883d0169c05233332ccf17aa956424c5
Ethereum Address: 0xAF4dE4076095A20A37E4E885B255C58f9917366e
Logo URI: https://www.fleato.com/images/flea120.png
Project Name: Fleato Marketplace
Project Summary: Fleato is the defi marketplace of physical goods and services. Buy, sell any physical good or service, and get paid in crypto. Turn your clutter into crypto. Earn up to 9% fleato rewards while doing so. Hodl, swap, trade, redeem, or stake your fleato coins. Read our whitepaper at https://docs.google.com/document/d/1fVNSPS3k6sr0JjqwV6XBn4I5tHaPO82Asm_XW-fQbL4/edit?usp=sharing 
Project Contact: mano.samy@fleato.com
Project Website: www.fleato.com

Mainnet/Testnet: Polygon / Mumbai
Additonal Notes: Fleato marketplace issues pre-minted fleato tokens to buyers and sellers on the marketplace upon proof of delivery. Staked fleato on products of your choice earns you a share of profits for every sale. Join the platform today. Download the mobile app at https://apps.apple.com/us/app/fleato/id1571515220 and https://play.google.com/store/apps/details?id=com.fleato.marketplace

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
