### ISSUE TITLE
Add {TRADE}: {Polytrade (PoS)}

### ISSUE THREAD

**Issue by Aboudjem** [maticnetwork/polygon-token-list#69]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Polytrade (PoS)
Token Symbol: TRADE
Decimals: 18
Polygon Address: 0x692AC1e363ae34b6B489148152b12e2785a3d8d6
Ethereum Address: 0x6e5970dbd6fc7eb1f29c6d2edf2bc4c36124c0c1
Logo URI: [polytrade.png](https://s2.coinmarketcap.com/static/img/coins/64x64/10465.png)
Project Name: Polytrade
Project Summary: Polytrade brings safe and insurance backed real world assets to crypto world. We will provide real world borrowers access to low interest and swift financing to free up critical working capital, tapped from crypto lenders.
Project Contact: support@polytrade.finance
Project Website: [Polytrade.finance](https://polytrade.finance/)

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
