### ISSUE TITLE
Add IQ: IQ

### ISSUE THREAD

**Issue by JustinCast** [maticnetwork/polygon-token-list#72]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: IQ
Token Symbol: IQ
Decimals: 18
Polygon Address: 0xB9638272aD6998708de56BBC0A290a1dE534a578
Ethereum Address: 0x579CEa1889991f68aCc35Ff5c3dd0621fF29b0C9
Logo URI: https://www.dropbox.com/sh/g97lq77b9mv9lfz/AABRnKWx9aiv6x8KShkIgDgla/Brain%20Logo%20Design-03.png?dl=0
Project Name: Everipedia
Project Summary: Everipedia's vision is to bring blockchain knowledge to the world and knowledge onto the blockchain, helping verify facts in an era of misinformation and unlocking a new class of use cases in the blockchain space.
Project Contact: https://t.me/everipedia
Project Website: https://everipedia.org/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by kesar** [comment]
@py-zoid worth mentioning that IQ is already in the wallet, but it has an outdated logo: 

https://everipedia.org/blog/announcing-the-iq-tokens-new-logo-and-big-brain-future

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
