### ISSUE TITLE
Add VISION: Vision Token 

### ISSUE THREAD

**Issue by apyvision** [maticnetwork/polygon-token-list#74]
- [x ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Vision Token
Token Symbol: VISION
Decimals: 18
Polygon Address: 0x034b2090b579228482520c589dbd397c53fc51cc
Ethereum Address: 0xF406F7A9046793267bc276908778B29563323996
Logo URI: https://assets.coingecko.com/coins/images/13288/large/apyvisionlogo200circle.png?1607059042
Project Name: APY Vision
Project Summary: APY.Vision is a historical analytics platform that provides clarity for liquidity providers and DeFi users with profit and loss tracking and useful liquidity pool fee calculators.
Project Contact: https://twitter.com/apyvision
Project Website: https://apy.vision

Mainnet/Testnet: Mainnet
Additional Notes: We support liquidity pool analytics, yield farming analysis, Uniswap V3 NFT analysis on Polygon/Matic.

**Comment by appumenon** [comment]
The child address provided is not as per mapping.
Currently the otken is ampped to [0xac51C4c48Dc3116487eD4BC16542e27B5694Da1b](https://etherscan.io/address/0xac51C4c48Dc3116487eD4BC16542e27B5694Da1b)
