### ISSUE TITLE
Add MWAT: RED MWAT

### ISSUE THREAD

**Issue by dugidox** [maticnetwork/polygon-token-list#75]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: RED MWAT
Token Symbol: MWAT
Decimals: 18
Polygon Address: 0x2B160EEA11604f81d5AdBBD2dcfE5B6Cd983652b
Ethereum Address: 0x6425c6BE902d692AE2db752B3c268AFAdb099D3b
Logo URI: https://s2.coinmarketcap.com/static/img/coins/64x64/2533.png
Project Name: Restart Energy Democracy
Project Summary: Restart Energy Democracy Platform (RED Platform) is a web-based platform which uses Blockchain
Technology to deliver users an extraordinary experience in the world of Carbon Offset, Sustainability
Certificates and Renewable Energy from producers to end customers.

RED platform is a social energy platform designed to revolutionize the way each of us interacts with
energy, the CO2 offset systems and the incentivization of renewable energy consumers and producers;

RED platform offers everyone the possibility to participate in the first tokenized CO2 offset platform,
earn from energy through the only 100% digital Energy Selling and Consultancy Franchise on the market
available in a 100% digital format.
Project Contact: support@redplatform.com
Project Website: https://redplatform.com/en/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by appumenon** [comment]
Child token added here is not as per the mapping @dugidox 
[0xE46F290Cd59195a83e757891430d8D517d16b334](https://etherscan.io/address/0xE46F290Cd59195a83e757891430d8D517d16b334) - Currently mapped to

**Comment by dugidox** [comment]
> Child token added here is not as per the mapping @dugidox [0xE46F290Cd59195a83e757891430d8D517d16b334](https://etherscan.io/address/0xE46F290Cd59195a83e757891430d8D517d16b334) - Currently mapped to


Etherscan link posted above points to totally different token not related to RED MWAT
Ethereum MWAT contract https://etherscan.io/token/0x6425c6be902d692ae2db752b3c268afadb099d3b
Mapped to Polygon contract https://polygonscan.com/token/0x2b160eea11604f81d5adbbd2dcfe5b6cd983652b

**Comment by py-zoid** [comment]
Updated project info in AllTokens tokenlist v1.8.0.
