### ISSUE TITLE
Add UCT: UCT Token

### ISSUE THREAD

**Issue by aztecmermaid** [maticnetwork/polygon-token-list#76]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Universal Community Trust / UCT Token
Token Symbol: UCT
Decimals: 18
Polygon Address: 0xfd5962484BE2c3574D70131BF5D452CcC7C69F67
Ethereum Address: 0xCC7dCc3F649Cb3932857d4edC6268e0eF4960995
Logo URI: https://www.uct-token.org/wp-content/uploads/2021/06/UCT-token-transp-500-500.png
Project Name: UCT Token
Project Summary: 1. The currency exists in a government-free jurisdiction.
2. As such, it is tax-exempt.
3. Which means it can't be regulated within UCT jurisdiction.
4. It is also backed by tangible commercial paper, in the form of liens.
5. Which means the token is not dependent upon sales to establish market value.
6. We already have a thriving community, which will soon enter exponential growth when we launch the tokens and the next tranche of £8.4 billion worth of liens are exchanged on the launch date.
7. Pre-launch, we have already established locked-in liquidity of $7.5B in two Crowdpools on Dodoex, via Polygon Mainnet, following the exchange of the first lien.
Project Contact: developers@uct-token.org
Project Website: https://www.uct-token.org
Mainnet/Testnet: Matic
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
