### ISSUE TITLE
Add UCTC: UCT Cash

### ISSUE THREAD

**Issue by aztecmermaid** [maticnetwork/polygon-token-list#77]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: UCT Cash
Token Symbol: UCTC
Decimals: 18
Polygon Address: 0xD4b42287F1EE04aF246aD792153C39D62733f826
Ethereum Address: 0x2707ab358B5383D087FE4736Da36c1C70179e3BD
Logo URI: https://www.uct-token.org/wp-content/uploads/2021/06/UCT-token-transp-500-500.png
Project Name: UCT Cash
Project Summary: 1. The currency exists in a government-free jurisdiction.
2. As such, it is tax-exempt.
3. Which means it can't be regulated within UCT jurisdiction.
4. It is also backed by tangible commercial paper, in the form of notes.
5. Which means the token is not dependent upon sales to establish market value.
6. We already have a thriving community, which will soon enter exponential growth when we launch the tokens and the next tranche of £8.4 billion worth of notes are exchanged on the launch date.
7. Pre-launch, we have already established locked-in liquidity of $7.5B in two Crowdpools on Dodoex, via Polygon Mainnet, following the exchange of the first note.
Project Contact: developers@uct-token.org
Project Website: https://www.uct-token.org
Mainnet/Testnet: Matic
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
