### ISSUE TITLE
Add UDT: Unlock Discount Token

### ISSUE THREAD

**Issue by julien51** [maticnetwork/polygon-token-list#78]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Unlock Discount Token
Token Symbol: UDT
Decimals: 18
Polygon Address: 0xf7e78d9c4c74df889a83c8c8d6d05bf70ff75876
Ethereum Address: 0x90de74265a416e1393a450752175aed98fe11517
Logo URI: https://github.com/unlock-protocol/unlock/blob/master/design/brand/1808-Unlock-Identity_Unlock-LogoMark-Circle.svg
Project Name: Unlock Protocol
Project Summary: The Unlock Protocol is a protocol for memberships where members cards are NFT with an expiration date
Project Contact: hello@unlock-protocol.com
Project Website: https://unlock-protocol.com/

Mainnet/Testnet: Yes
Additonal Notes: NA

**Comment by py-zoid** [comment]
Mainnet/Testnet: Mainnet

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
