### ISSUE TITLE
Add WEB3: Arch Ethereum Web3

### ISSUE THREAD

**Issue by dlarrain** [maticnetwork/polygon-token-list#79]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Arch Ethereum Web3
Token Symbol: WEB3
Decimals: 18
Polygon Address: 0xBcD2C5C78000504EFBC1cE6489dfcaC71835406A
Ethereum Address: 0xe8e8486228753E01Dbc222dA262Aa706Bd67e601
Logo URI: https://arch-finance-basket-logos.s3.amazonaws.com/ETHWEB3.png
Project Name: Arch
Project Summary: The Arch Ethereum Web3 Token is comprised of governance tokens from the major decentralized protocols. Its objective is to track the returns of the Ethereum Web3 Index (a broad market index, considered a gauge for the overall web3 ecosystem). This well-diversified asset provides market-weighted exposure to a wide selection of sectors, and its constituents represent roughly 70% of the market capitalization in the Ethereum Web3 Index.
Project Contact: hello@archfinance.io
Project Website: https://www.archfinance.io/

Mainnet/Testnet: Mainnet
Additional Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
