### ISSUE TITLE
Add BRZ: BRZ Token

### ISSUE THREAD

**Issue by m4rlyson** [maticnetwork/polygon-token-list#8]
- [X] #13

**Please provide the following information for your token.**

Token Name: BRZ
Token Symbol: BRZ Token
Decimals: 4
Polygon Address: 0x491a4eB4f1FC3BfF8E1d2FC856a6A46663aD556f
Ethereum Address: 0x420412e765bfa6d85aaac94b4f7b708c89be2e2b
Logo URI: https://brztoken.io/img/svgs/brz.svg
Project Name: Brazilian Digital Token
Project Summary: The BRZ Token is the Brazilian stablecoin in circulation that allows Brazilians to directly access different pairs of assets on exchanges and to trade a stable currency pegged to the brazilian real (BRL) on a global scale.
Project Contact: contact@brztoken.io
Project Website: https://brztoken.io/

**Comment by py-zoid** [comment]
This token doesn't seemed to be mapped. To map the token please raise a request on https://mapper.polygon.technology. Closing this issue.
