### ISSUE TITLE
Add PRUF: PRUF

### ISSUE THREAD

**Issue by jamesBsmyth** [maticnetwork/polygon-token-list#81]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: PRUF
Token Symbol: PRUF
Decimals: 18
Polygon Address: 0xAdf72D32E511eE00c6E0FF5D62Cd5C7C40A6aDEA
Ethereum Address: 0xa49811140e1d6f653dec28037be0924c811c4538
Logo URI: https://pruf.io/assets/images/prufcircle-1200x1200.png
Project Name: PRüF Protocol
Project Summary: The PRüF Protocol brings legitimacy and permanence to tokenized assets, endowing standards compliant tokens with super-powers. PRüF enabled NFTs and assets deliver lasting value through permanent storage,
future-proof protocols, and DAO governance.
Project Contact: james@pruf.io
Project Website:https://pruf.io

Mainnet/Testnet: Mainnet, Protocol in testnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
