### ISSUE TITLE
Add ROYA: Royale (PoS)

### ISSUE THREAD

**Issue by RoyaleFinance** [maticnetwork/polygon-token-list#82]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Royale (PoS)
Token Symbol: ROYA
Decimals:18
Polygon Address: 0x0bD820aD2d7Ab7305b5C9538ba824C9b9bEb0561
Ethereum Address: 0x7eaf9c89037e4814dc0d9952ac7f888c784548db
Logo URI: https://assets.coingecko.com/coins/images/13602/small/roya.png?1636031771
Project Name: Royale Finance
Project Summary: Royale Finance is an industry-focused decentralized lending protocol and blockchain game launchpad. Its purpose is to create Web 3.0 decentralized liquidity funding solutions using DeFi primitives to support the innovation of gaming products and platforms.

Project Contact: team@royale.finance
Project Website: https://royale.finance

Mainnet/Testnet: https://app.royale.finance
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
