### ISSUE TITLE
Add EXS : ExSports

### ISSUE THREAD

**Issue by SanctumVenture** [maticnetwork/polygon-token-list#83]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: EXS
Token Symbol: EXS
Decimals: 18
Polygon Address: 0x11928CFCbC0398b9206C6D57ff7D8201555D6773
Ethereum Address: 0x7331355e2DaD3b55f9ce0fd460D082558952099e
Logo URI: https://img.ex-sports.io/imgs/icons/exs.png
Project Name: ExSports 
Project Summary:  EX Sport Starz is a platform that allows sport fans to buy, trade and sell digital sport collectibles. The app offers a variety of sports and has a special reward program for the collectors, athletes and sport fans.
Project Contact: technical@ex-sports.io
Project Website: https://www.ex-sports.io/

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
