### ISSUE TITLE
Add {MYST}: {Mysterium}

### ISSUE THREAD

**Issue by EvheniyaSh** [maticnetwork/polygon-token-list#85]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Mysterium
Token Symbol: MYST
Decimals: 18
Polygon Address: 0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3
Ethereum Address: 0x4Cf89ca06ad997bC732Dc876ed2A7F26a9E7f361
Logo URI: https://drive.google.com/file/d/1eaq6uo0ctS0ucAEnZXS206j1uDqEywAO/view?usp=sharing
Project Name: Mysterium Network
Project Summary: Mysterium Network is an open-source ecosystem of protocols, tools, and Web3 infrastructure making the internet borderless and accessible for all. The network gives both users and builders the tools they need to defend online privacy, anonymous expression, and equal access to information. Mysterium held a token sale through which it raised $14 million CHF.

Mysterium is powered by its permissionless, peer-to-peer network. Anyone can turn their device into a node and rent their spare internet resources, such as bandwidth or IP address, in exchange for cryptocurrency. The network is tamper-proof, anonymous, and encrypted like Tor, but with superior usability, stability and speed.

Mysterium’s B2B Network-as-a-Service lays the groundwork for all kinds of enterprise-level services to be built, including the project's flagship product, the [Mysterium VPN](https://www.mysteriumvpn.com/), available for Android, Windows, Mac and Linux (iOS in 2022). Developers and entrepreneurs can build private, censorship-resistant tools, and businesses can make their products globally accessible and secure. The technology is fully compatible with both Web2 and Web3 platforms and can be integrated with VPNs, proxy services, DeFi wallets, browsers, search engines, data scraping solutions, and streaming apps, building privacy and censorship-resistance into the apps we already use.
Project Contact: info@mysterium.network 
Project Website: https://www.mysterium.network/

Mainnet/Testnet: https://github.com/MysteriumNetwork
Additonal Notes:

**Comment by py-zoid** [comment]
Already added to the tokenlist but please provide a .svg image link for logoURI.

**Comment by py-zoid** [comment]
Using this logoURI https://wallet-asset.matic.network/img/tokens/myst.svg instead of the one provided. If you wish to change the logoURI, please raise an update request.
