### ISSUE TITLE
Add SWASH: Swash Token

### ISSUE THREAD

**Issue by ebkhalilzadeh** [maticnetwork/polygon-token-list#86]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Swash Token
Token Symbol: SWASH
Decimals: 18
Polygon Address: 0xbA3CB8329D442E6F9Eb70fafe1E214251df3D275
Ethereum Address: 0xA130E3a33a4d84b04c3918c4E5762223Ae252F80
Logo URI: https://github.com/swashapp/token/blob/main/logo/Logo.png
Project Name: Swash 
Project Summary: Swash is an ecosystem of tools and services that enable people, businesses, and developers to unlock the latent value of data by pooling, securely sharing, and monetizing its value.
Project Contact: contact@swashapp.io
Project Website: https://swashapp.io/

Mainnet/Testnet: -
Additonal Notes: -

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
