### ISSUE TITLE
Add PAINT: Paint

### ISSUE THREAD

**Issue by keirongulrajani** [maticnetwork/polygon-token-list#87]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

Token Name: Paint
Token Symbol: PAINT
Decimals: 18
Polygon Address: 0x7c28F627eA3aEc8B882b51eb1935f66e5b875714
Ethereum Address: 0x4C6eC08CF3fc987c6C4BEB03184D335A2dFc4042
Logo URI: https://gateway.pinata.cloud/ipfs/QmSqt6RAgNYWq3kJRhEoLquY2xcZ7QXAJGovaeaxmZYCVJ
Project Name: MurAll
Project Summary: MurAll is a 2048x1024px digital mural that anyone can draw on without restriction. MurAll requires PAINT - a fixed supply token synonymous with real-life paint, which is burned in the painting transaction. Painting on MurAll also mints a MURALL NFT of the artwork for the artist to keep.
Project Contact: keiron@murall.art
Project Website: https://murall.art

Mainnet/Testnet: Mainnet

Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
