### ISSUE TITLE
Add YUP: Yup

### ISSUE THREAD

**Issue by zkSPARKs** [maticnetwork/polygon-token-list#88]
- [ x ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Yup
Token Symbol: YUP
Decimals: 18
Polygon Address: 0x086373fad3447F7F86252fb59d56107e9E0FaaFa
Ethereum Address: 0x69bbc3f8787d573f1bbdd0a5f40c7ba0aee9bcc9
Logo URI: https://i.imgur.com/QC2UG1G.png
Project Name: Yup
Project Summary: Social network for curators, reputation mechanism.
Project Contact: Yup Team, community@yup.io
Project Website: https://yup.io

Mainnet/Testnet: Mainnet
Additonal Notes: Excited to join the Polygon ecosystem!

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
