### ISSUE TITLE
Add DMR: Dreamr

### ISSUE THREAD

**Issue by dreamrsunite** [maticnetwork/polygon-token-list#89]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Dreamr Platform Token
Token Symbol: DMR
Decimals: 18
Polygon Address: 0x955ce23f20217a6aa205620b40ede4c9e83d325f
Ethereum Address: 0xf74941046389c78f12fe44784c0ec9ca7ceb7dc2
Logo URI: ipfs://QmepiCxpZqks5sjB6r55gErgCXqhGdCsbXYpuauG5yxCyB
Project Name: Dreamr
Project Summary: Web3 Social+NFT+DeFi Platform, a suite of tools to make the pursuit of big dreams more practical. 
Project Contact: chris@dreamrlabs.org
Project Website: https://dreamr.app, https://dreamrlabs.org

Mainnet/Testnet: Mainnet
Additonal Notes: Hybrid Mobile App, Wallet, Marketplace, NFT Launchpad

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
