### ISSUE TITLE
Add CHP: CoinPoker Chips

### ISSUE THREAD

**Issue by CoinPokerOfficial** [maticnetwork/polygon-token-list#90]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: CoinPoker Chips
Token Symbol: CHP
Decimals: 18
Polygon Address: https://polygonscan.com/token/0x59b5654a17ac44f3068b3882f298881433bb07ef
Ethereum Address: https://etherscan.io/token/0x0a6e18fb2842855c3af925310b0f50a4bfa17909
Logo URI: https://coinpoker.com/assets/img/logox2.png
Project Name: CoinPoker
Project Summary: CoinPoker is a cryptocurrency-powered online poker room built on the principles of transparency, security, and fair play.
Project Contact: info@coinpoker.com
Project Website: https://coinpoker.com/

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
