### ISSUE TITLE
PDAO:PlannerDAO Opportunity Index

### ISSUE THREAD

**Issue by larseny** [maticnetwork/polygon-token-list#91]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: PlannerDAO Opportunity Index
Token Symbol: PDAO
Decimals: 18
Polygon Address: waiting
Ethereum Address: 0xa025f41f1A973E6649931f3AC96979071bda4c9F
Logo URI: https://uploads-ssl.webflow.com/6096909a9f570cf818e33cf5/61e658c8fb13b00b5a4c40c2_Untitled%20design.png
Project Name: PlannerDAO
Project Summary:  https://www.prnewswire.com/news-releases/plannerdao-co-founder-steve-larsen-cpa-cfp-launches-comprehensive-digital-asset-index-for-financial-planners-301462751.html
Project Contact: Steve Larsen, CPA, CFP
Project Website: https://www.plannerdao.com/pdao

Mainnet/Testnet: Mainnet
Additional Notes: Hello, I have submitted a few requests and the token must have been in the queue before you switched to the new system. Please let me know if you need anything additional. Thanks! Steve Larsen, steve@larsenfin.com

**Comment by larseny** [comment]
Hi, I have received my Polygon token address: 0x2b4fa97b84698dc1540d13d33754757bac3c8115

**Comment by py-zoid** [comment]
Updated project info in AllTokens tokenlist v1.8.0.
