### ISSUE TITLE
Add MM: Mintopoly Money

### ISSUE THREAD

**Issue by labeldot** [maticnetwork/polygon-token-list#93]
- [√] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Mintopoly Money
Token Symbol: MM
Decimals: 8
Polygon Address: 0xf6a09deadf5a10aa7822d95e3228b2315de8f6fa
Ethereum Address: 0xf6a09deadf5a10aa7822d95e3228b2315de8f6fa
Logo URI: https://etherscan.io/token/images/mintopolymoney_32.png
Project Name: Mintopoly 
Project Summary: Mintopoly is a blockchain simulation game powered by NFT Mintopoly Cards and Mintopoly Money (MM) token – our in-game currency airdropped freely to hundreds of top players each week with uses throughout the Mintopoly ecosystem.
Project Contact: mr@mintopoly.io
Project Website: https://mintopoly.io

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Included in AllTokens v1.2.0.
