### ISSUE TITLE
Add {GET}: {GET_Protocol}

### ISSUE THREAD

**Issue by OlivierBiggs** [maticnetwork/polygon-token-list#95]
- [X] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: GET Protocol
Token Symbol: GET
Decimals: 18
Polygon Address: 0xdb725f82818de83e99f1dac22a9b5b51d3d04dd4
Ethereum Address: 0x8a854288a5976036a725879164ca3e91d30c6a1b
Logo URI (svg): https://drive.google.com/drive/folders/1lHkdKlKLyXjXJsZM2SMuavmzIDiIAgbU
Project Name: GET Protocol
Project Summary: GET Protocol provides infrastructure and tooling that enables ticketing companies worldwide to issue cutting edge NFT tickets.
Project Contact: https://discord.com/invite/jTkCWGASEw
Project Website: https://get-protocol.io

Mainnet/Testnet: Mainnet
Additonal Notes:

**Comment by py-zoid** [comment]
Update project information in AllTokens tokenlist v1.8.0.
