### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by jakenft** [maticnetwork/polygon-token-list#96]
- [ ] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: NFT Protocol
Token Symbol: NFT
Decimals: 18
Polygon Address: 0x65c2C7095bFDC8460d7302b6a95c66cD5D8B2CFf
Ethereum Address: 0xcB8d1260F9c92A3A545d409466280fFdD7AF7042
Logo URI (svg): ![nft-protocol](https://user-images.githubusercontent.com/90467447/156639904-7717511d-0939-44e4-bafa-1eb7ec92e895.svg)
Project Name: NFT Protocol
Project Summary: docs.nft.org
Project Contact: jake@nft.org
Project Website: nft.org

Mainnet/Testnet:
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0. Please raise a new issue to update the token's logURI with a working link.
