### ISSUE TITLE
Add KPT: Kitty Party Reward Token

### ISSUE THREAD

**Issue by cryptobugbear** [maticnetwork/polygon-token-list#99]
- [x] I understand that token listing is not required to use the Polygon Wallet with a token.

**Please provide the following information for your token.**

Token Name: Kitty Party Reward Token
Token Symbol: KPT
Decimals: 18
Polygon Address: 0x7d369731e3d7f86417aa86ef4be26e309080bd2f
Ethereum Address: 0x444f20a5d578862bf84b6d14ec3ca0c8be8e555f
Logo URI (svg): https://bafkreiawezzhlphckhopkolrkxsz4mtayjz4cjxz4bgsvvkjsclqacf2be.ipfs.nftstorage.link/
Project Name: Kitty Party Finance
Project Summary: Kitty Party enables community led yield and wealth creation.
Project Contact: wizgotD@protonmail.com
Project Website: kittyparty.finance

Mainnet/Testnet:  Mainnet - https://beta.kittyparty.finance/#/  Testnet - https://testnet.kittyparty.finance/#/
Additonal Notes:

**Comment by py-zoid** [comment]
Added to AllTokens tokenlist v1.8.0.
